---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - action.yml
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch: {}

defaults:
  run:
    shell: sh

jobs:
  get-versions:
    name: Get 3 latest versions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      versions: ${{ steps.prepare-list.outputs.versions }}
    steps:
      - name: Get releases
        id: github-releases
        uses: yakubique/github-releases@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: "woodruffw/zizmor"
          sort: "desc"
      - name: Prepare list
        id: prepare-list
        env:
          RELEASES_AMOUNT: "3"
        run: |
          versions=$(echo '${{ steps.github-releases.outputs.releases }}' \
            | jq -c -r --arg n "${RELEASES_AMOUNT}" '.[0:($n | tonumber)] | map(sub("^v"; "")) | . += ["latest"]')
          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
  setup-zizmor:
    name: Setup zizmor
    needs: [get-versions]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup zizmor
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Perform analysis
        continue-on-error: true
        run: zizmor .
  setup-zizmor-in-container:
    name: Setup zizmor in container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ${{ matrix.os }}:latest
    strategy:
      fail-fast: false
      matrix:
        os: ["fedora", "ubuntu"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup zizmor
        uses: ./
      - name: Perform analysis
        continue-on-error: true
        run: zizmor .
  test-force:
    name: Test force
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        force: ["true", "false"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup zizmor 1
        id: setup-zizmor-1
        uses: ./
      - name: Setup zizmor 2
        id: setup-zizmor-2
        uses: ./
        with:
          force: ${{ matrix.force }}
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "Wrong \"installed\" output from setup-zizmor-1" \
            "${{ steps.setup-zizmor-1.outputs.installed }}" \
            "true"
          test_equal "Wrong \"installed\" output from setup-zizmor-2" \
            "${{ steps.setup-zizmor-2.outputs.installed }}" \
            "${{ matrix.force }}"
